const jokesArray = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "I used to play piano by ear, but now I use my hands.",
  "Why don't oysters donate to charity? Because they're shellfish.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call an alligator in a vest? An investigator!",
  "I'm on a whiskey diet. I've lost three days already.",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
];

// code to get random number between 1 and 200
const getRandomNumber = () => {
  return Math.floor(Math.random() * 200) + 1;
};

const randomNumber = getRandomNumber();

console.log(jokesArray[randomNumber]);
let mainBody = document.getElementsByClassName("mainBody")[0];
// mainBody.style.color='red'
mainBody.innerHTML = jokesArray[randomNumber];

// REFRESH BUTTON LOGIC 
function refreshPage() {
  location.reload();
}